### PR TITLE
Fix deployAll for flexible projects

### LINKED ISSUE #277: Fix appengineDeployAll task for flexible projects

### PR DESCRIPTION
**Pull request by TadCordle**
Fixes #277

### CODE REVIEW

File: src/main/java/com/google/cloud/tools/maven/StageMojo.java [hunk 1]
```diff
@@ -247,7 +244,11 @@ public void execute() throws MojoExecutionException, MojoFailureException {
     }
   }
 
-  protected boolean isStandardStaging() {
+  protected boolean isStandardStaging() throws MojoExecutionException {
+    if (appengineWebXml == null) {
+      appengineWebXml =
+          new AppEngineWebXml(new File(sourceDirectory.toString() + "/WEB-INF/appengine-web.xml"));
```
Comment (coollog) [inline src/main/java/com/google/cloud/tools/maven/StageMojo.java]: Should probably use path resolution to build the path rather than string concatenation.

File: src/main/java/com/google/cloud/tools/maven/StageMojo.java [hunk 2]
```diff
@@ -268,7 +269,7 @@ protected void configureDockerfileDefaultLocation() {
    * <p>Called during {@link #execute()}, subclasses can override to provide a different value for
    * {@link #appEngineDirectory}.
    */
-  protected void configureAppEngineDirectory() {
+  protected void configureAppEngineDirectory() throws MojoExecutionException {
```
Comment (coollog) [inline src/main/java/com/google/cloud/tools/maven/StageMojo.java]: Is this `MojoExecutionException` used?

File: src/main/java/com/google/cloud/tools/maven/DeployAllMojo.java [hunk 3]
```diff
@@ -46,6 +46,15 @@ public void execute() throws MojoExecutionException, MojoFailureException {
       if (yaml.exists()) {
         getLog().info("deployAll: Preparing to deploy " + yamlName);
         deployables.add(yaml);
+      } else if (!isStandardStaging()) {
```
Comment (coollog) [inline src/main/java/com/google/cloud/tools/maven/DeployAllMojo.java]: I was thinking this logic could probably be organized as flexible vs. standard as the top-level condition, rather than having the standard yaml existence be the default check. In the case that the user was using flexible but had yamls in the standard locations, then it would be deploying possibly incorrect yamls. It might be fine, but it seems a bit off to me.

File: src/main/java/com/google/cloud/tools/maven/StageMojo.java (hunk 2 above)
Comment (TadCordle) [reply src/main/java/com/google/cloud/tools/maven/StageMojo.java]: This method is overridden in AbstractSingleYamlDeployMojo and it's used there.

File: src/main/java/com/google/cloud/tools/maven/DeployAllMojo.java (hunk 3 above)
Comment (TadCordle) [reply src/main/java/com/google/cloud/tools/maven/DeployAllMojo.java]: As far as I understand, in flexible projects we do want to check for yamls to deploy in both the source directory and the staging directory, but I'm not sure. @loosebazooka?

File: src/main/java/com/google/cloud/tools/maven/StageMojo.java (hunk 2 above)
Comment (coollog) [reply src/main/java/com/google/cloud/tools/maven/StageMojo.java]: Hmm, it seems that `isStandardStaging` should probably not set the `appengineWebXml` (like a method that should be a boolean getter should probably not be changing the state of the object).

Comment (coollog) [reply src/main/java/com/google/cloud/tools/maven/StageMojo.java]: Referring to `AbstractSingleYamlDeployMojo` using `isStandardStaging`, which is why it seems to throw the `MojoExecutionException`.

File: src/main/java/com/google/cloud/tools/maven/DeployAllMojo.java (hunk 3 above)
Comment (TadCordle) [reply src/main/java/com/google/cloud/tools/maven/DeployAllMojo.java]: Oh wait I see what you're saying I think

File: src/main/java/com/google/cloud/tools/maven/DeployAllMojo.java [hunk 4]
```diff
@@ -38,17 +38,51 @@ public void execute() throws MojoExecutionException, MojoFailureException {
...
+    String[] configYamls = {"cron.yaml", "dispatch.yaml", "dos.yaml", "index.yaml", "queue.yaml"};
+    File appYaml = stagingDirectory.toPath().resolve("app.yaml").toFile();
+    if (appYaml.exists()) {
+      addDeployable(appYaml);
+    }
+
+    if (isStandardStaging()) {
+      // Check staging directory for app.yaml
+      if (!appYaml.exists()) {
+        throw new MojoExecutionException("Failed to deploy all: app.yaml not found.");
```
Comment (coollog) [inline src/main/java/com/google/cloud/tools/maven/DeployAllMojo.java]: nit: since the exception here is the same as the exception for flexible, this could probably be split up into two stages, one for deploying app.yaml, and one for deploying the others, such that this code doesn't have to be duplicated.

File: src/main/java/com/google/cloud/tools/maven/DeployAllMojo.java [hunk 5]
```diff
@@ -38,17 +38,51 @@ public void execute() throws MojoExecutionException, MojoFailureException {
...
-      "app.yaml", "cron.yaml", "dispatch.yaml", "dos.yaml", "index.yaml", "queue.yaml"
-    };
-    for (String yamlName : validYamls) {
-      File yaml = stagingDirectory.toPath().resolve(yamlName).toFile();
-      if (yaml.exists()) {
-        getLog().info("deployAll: Preparing to deploy " + yamlName);
-        deployables.add(yaml);
+    String[] configYamls = {"cron.yaml", "dispatch.yaml", "dos.yaml", "index.yaml", "queue.yaml"};
+    File appYaml = stagingDirectory.toPath().resolve("app.yaml").toFile();
+    if (appYaml.exists()) {
```
Comment (coollog) [inline src/main/java/com/google/cloud/tools/maven/DeployAllMojo.java]: nit: Looks like `addDeployable` could even include the existence check

File: src/main/java/com/google/cloud/tools/maven/DeployAllMojo.java [hunk 6]
```diff
@@ -38,26 +38,48 @@ public void execute() throws MojoExecutionException, MojoFailureException {
...
     }
 
-    String[] validYamls = {
-      "app.yaml", "cron.yaml", "dispatch.yaml", "dos.yaml", "index.yaml", "queue.yaml"
-    };
-    for (String yamlName : validYamls) {
-      File yaml = stagingDirectory.toPath().resolve(yamlName).toFile();
+    if (isStandardStaging()) {
+      // Check staging directory for all yamls
+      String[] validYamls = {
```
[the remark this answers is not in the document]
Comment (TadCordle) [reply src/main/java/com/google/cloud/tools/maven/DeployAllMojo.java]: Looks like I fixed these right before you commented on them.

File: src/main/java/com/google/cloud/tools/maven/DeployAllMojo.java [hunk 7]
```diff
@@ -38,17 +38,51 @@ public void execute() throws MojoExecutionException, MojoFailureException {
...
+        if (appYaml.exists()) {
+          addDeployable(appYaml);
+        } else {
+          throw new MojoExecutionException("Failed to deploy all: app.yaml not found.");
+        }
+      }
+
+      // Look appengine directory for config yamls
+      configureAppEngineDirectory();
+      for (String yamlName : configYamls) {
```
Comment (coollog) [inline src/main/java/com/google/cloud/tools/maven/DeployAllMojo.java]: nit: This could probably also be combined with the loop for standard, just changing the directory it resolves for.

File: src/main/java/com/google/cloud/tools/maven/StageMojo.java [hunk 8]
```diff
@@ -216,15 +215,15 @@ public void execute() throws MojoExecutionException, MojoFailureException {
...
-
     configureAppEngineDirectory();
 
     if (isStandardStaging()) {
       getLog().info("Detected App Engine standard environment application.");
 
       // force runtime to 'java' for compat projects using Java version >1.7
+      AppEngineWebXml appengineWebXml =
+          new AppEngineWebXml(
+              new File(sourceDirectory.toPath().resolve("WEB-INF/appengine-web.xml").toString()));
```
Comment (loosebazooka) [inline src/main/java/com/google/cloud/tools/maven/StageMojo.java]: `.resolve("WEB-INF").resolve("appengine-web.xml")`

but also, maybe I missed some older comments, why did we need to move this around?

Comment (TadCordle) [reply src/main/java/com/google/cloud/tools/maven/StageMojo.java]: I wanted to call `isStandardStaging()` in `DeployAllMojo`, but the original implementation used `appengineWebXml`, which was just a private field that was set in `StageMojo.execute(). So whenever I tried to call `isStandardStaging()`, `appengineWebXml` was null and I'd get an error. So I changed `isStandardStaging()` to not rely on the field, realized `appengineWebXml` wasn't used anywhere else, and reduced its scope.

File: src/main/java/com/google/cloud/tools/maven/StageMojo.java [hunk 9]
```diff
@@ -248,7 +252,7 @@ public void execute() throws MojoExecutionException, MojoFailureException {
   }
 
   protected boolean isStandardStaging() {
-    return appengineWebXml.exists();
+    return Files.exists(sourceDirectory.toPath().resolve("WEB-INF/appengine-web.xml"));
```
Comment (loosebazooka) [inline src/main/java/com/google/cloud/tools/maven/StageMojo.java]: probably want to resolve resolve here too.

File: src/main/java/com/google/cloud/tools/maven/StageMojo.java [hunk 10]
```diff
@@ -216,15 +215,20 @@ public void execute() throws MojoExecutionException, MojoFailureException {
 
     getLog().info("Staging the application to: " + stagingDirectory);
 
-    appengineWebXml =
-        new AppEngineWebXml(new File(sourceDirectory.toString() + "/WEB-INF/appengine-web.xml"));
-
     configureAppEngineDirectory();
```
Comment (loosebazooka) [inline src/main/java/com/google/cloud/tools/maven/StageMojo.java]: feels like you could just resolve appengienWeb.xml here and do an if(exists) to start this loop?

Comment (loosebazooka) [reply src/main/java/com/google/cloud/tools/maven/StageMojo.java]: unless isStandardStaging is used somewhere else.

Comment (TadCordle) [reply src/main/java/com/google/cloud/tools/maven/StageMojo.java]: I use isStandardStaging in the deploy all task, which is why I changed this in the first place.

Comment (TadCordle) [reply src/main/java/com/google/cloud/tools/maven/StageMojo.java]: Also in `AbstractSingleYamlDeployMojo`.
