### PR TITLE
Fail early when trying to start dev server with flexible app

### LINKED ISSUE #51: Provide better error messages when invoking Dev Appserver for non-standard env apps

### PR DESCRIPTION
**Pull request by meltsufin**
Fixes #51 

@loosebazooka

### CODE REVIEW

File: src/main/java/com/google/cloud/tools/maven/RunMojo.java [hunk 1]
```diff
@@ -214,6 +214,28 @@ protected void workAroundNonJava7Version() {
...
   }
 
+  /**
+   * Determine if the application is a Standard Environment app.
+   */
+  protected boolean isStandardEnvironmentApp() {
+    return mavenProject != null
+        && mavenProject.getBuild() != null
+        && new File(
+        mavenProject.getBuild().getDirectory() + "/" + mavenProject.getBuild().getFinalName()
```
Comment (loosebazooka) [inline src/main/java/com/google/cloud/tools/maven/RunMojo.java]: you want to check on the build directory? or the source directory?

Comment (loosebazooka) [inline src/main/java/com/google/cloud/tools/maven/RunMojo.java]: oh this is for the devappserver? Would it make sense to indicate the intention of the method to check the build directory to make it more explicit?

Comment (meltsufin) [inline src/main/java/com/google/cloud/tools/maven/RunMojo.java]: Since, we're running the Dev Appserver from the build dir, I thought it would be more appropriate to check there, rather than in the source. I'll modify the comment to make it more clear.

**Comment by meltsufin** [comment]
@loosebazooka See comment updates.

**Comment by meltsufin** [comment]
@loosebazooka PTAL

File: src/main/java/com/google/cloud/tools/maven/RunMojo.java (hunk 1 above)
Comment (loosebazooka) [inline src/main/java/com/google/cloud/tools/maven/RunMojo.java]: feel like spacing is off here
```
&& new File(
    mavenProejct....
```

**Comment by loosebazooka** [comment]
just a little thing, otherwise LGTM
